spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: productModule
        uri: lb://ProductService
        predicates:
        - Path=/product/**
      - id: stockModule
        uri: lb://StockService
        predicates:
        - Path=/stock/**
            
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8761/eureka/

